// Code generated by aocgen; DO NOT EDIT.
package year2021

import (
	"strconv"
	"strings"
)

type Day02 struct{}

type Position struct{
	horizontal int
	depth int
	aim int
}

func (p *Position) move(direction string, step int) {
	switch direction {
	case "forward":
		p.horizontal += step
	case "up":
		p.depth -= step
	case "down":
		p.depth += step
	}
}

func (p *Position) move2nd(direction string, step int) {
	switch direction {
	case "forward":
		p.horizontal += step
		p.depth += p.aim*step
	case "up":
		p.aim -= step
	case "down":
		p.aim += step
	}
}

func (p *Position) calcPosition() int {
	return p.horizontal*p.depth
}

func (p Day02) PartA(lines []string) any {
	var position Position
	for _, value := range lines {
		s := strings.Split(value, " ")
		step, _ := strconv.Atoi(strings.ReplaceAll(s[1], "\r", ""))
		position.move(s[0], step)
	}
	return position.calcPosition()
}

func (p Day02) PartB(lines []string) any {
	var position Position
	for _, value := range lines {
		s := strings.Split(value, " ")
		step, _ := strconv.Atoi(strings.ReplaceAll(s[1], "\r", ""))
		position.move2nd(s[0], step)
	}
	return position.calcPosition()
}
