// Code generated by aocgen; DO NOT EDIT.
package year2021

import (
	"strconv"
)

type Day01 struct{}

func (p Day01) PartA(lines []string) any {
	var lastLine int
	var countIncrease int = 0
	for line, value := range lines {
		lineNumb, _ := strconv.Atoi(value)
		if line == 0 {
			lastLine = lineNumb
			continue
		}
		if lastLine < lineNumb {
			countIncrease++
		}
		lastLine = lineNumb
	}
	return strconv.Itoa(countIncrease)
}

func (p Day01) PartB(lines []string) any {
	var countIncrease int
	var length int = len(lines)
	for i := 3; i < length; i++ {
		lineNumb0, _ := strconv.Atoi(lines[i-3])
		lineNumb1, _ := strconv.Atoi(lines[i-2])
		lineNumb2, _ := strconv.Atoi(lines[i-1])
		lineNumb3, _ := strconv.Atoi(lines[i])
		if (lineNumb0+lineNumb1+lineNumb2) < (lineNumb1+lineNumb2+lineNumb3) {
			countIncrease++
		}
	}
	return strconv.Itoa(countIncrease)
}
